// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/TodoApp/AppBar.vue')['default']
    Avatar: typeof import('./components/TodoApp/Avatar.vue')['default']
    Gradient: typeof import('./components/TodoApp/Gradient.vue')['default']
    GradientColor: typeof import('./components/TodoApp/GradientColor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./components/TodoApp/Task.vue')['default']
    Todo: typeof import('./components/TodoApp/Todo.vue')['default']
    TodoDetail: typeof import('./components/TodoApp/TodoDetail.vue')['default']
    TodoList: typeof import('./components/TodoApp/TodoList.vue')['default']
  }
}
